Gem::Specification.new do |s|
  s.name = "rails_css_themes"
  s.summary = "Support for stylesheet themes for Rails applications"
  s.description = "This gem allows you to have your themes inside stylesheet/theme. It modifies paths generated by stylesheet_link_tag to include the theme directory"
  s.files = `git ls-files`.split("\n")
  s.version = "1.0.0"
  s.authors = [ "GING - DIT - UPM" ]
  s.add_development_dependency('rspec-rails', '~> 2.5.0')
end
